language: java
matrix:
  include:
    - name: OpenJDK 11
      jdk: openjdk11

before_cache:
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
    - $HOME/google-cloud-sdk
env:
  global:
    - CLOUDSDK_CORE_DISABLE_USAGE_REPORTING=true
    - CLOUDSDK_CORE_DISABLE_PROMPTS=true
install:
  # https://github.com/travis-ci/travis-ci/issues/8408
  - unset _JAVA_OPTIONS

  # check if cloud SDK was installed (/bin exists)
  # travis auto creates cache directories, so remove it before install
  - if [ ! -d $HOME/google-cloud-sdk/bin ]; then
    rm -rf $HOME/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash;
    fi
  # make our installed cloud sdk take precedence
  - source $HOME/google-cloud-sdk/path.bash.inc
  # update gcloud
  - gcloud components update --quiet
  # add App Engine component to Cloud SDK
  - gcloud components install app-engine-java --quiet

script:
  - ./gradlew clean check