version: '3'

services:
  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    expose:
      - 6379
  shortit:
    image: tushard123/shortit:latest
    container_name: shortit
    depends_on:
    - redis
    ports:
    - "8080:8080"
    expose:
      - 8080